name: Testing
on: push

jobs:
    test_airline_project: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ejeuta los tests de Django
              run:
                pip3 install --user django
                python3 manage.py test